FROM node:20-alpine
WORKDIR /usr/src/app
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
COPY credentials.json /app/credentials.json

# Install dependencies
COPY package.json yarn.lock* package-lock.json* ./
RUN if [ -f yarn.lock ]; then yarn install --production --frozen-lockfile; else npm ci --omit=dev; fi

# Copy source code
COPY . .

# Build TypeScript sources
RUN npm run build

CMD ["npm", "run", "serve"]
